### ISSUE TITLE
Error in line import geohash

### ISSUE THREAD

**Issue by solucionesmipc** [owntracks/pista#34]
Hi:
i receive this error message:

might have changed url?

Traceback (most recent call last):
  File "o2s.py", line 15, in <module>
    from owntracks.revgeo import RevGeo
  File "/etc/mosquitto/pista/pista/owntracks/revgeo.py", line 12, in <module>
    import geohash # https://code.google.com/p/python-geohash/
ImportError: No module named geohash

please help:

thanks a lot

**Comment by jpmens** [comment]
You haven't installed the requirements.

**Comment by solucionesmipc** [comment]
thanks a lot, i will try with a new clean installation.

regards.

Diego

**Comment by solucionesmipc** [comment]
Hi:

i have enough with o2s.py running.

please, can you share the suggested configuration to add o2s.py to supervisor?

 i tried

[program:o2s]
directory = /path/to/o2s
command = /path/to/02s.py

program does not find o2s.conf

thanks again

Diego

**Comment by sumnerboy12** [comment]
Your command path has a typo I believe.

**Comment by solucionesmipc** [comment]
Hi:

no typo, the real data i have is

[program:o2s]
directory = /pista/o2s
command = /pista/02s.py

thanks

Diego

**Comment by jpmens** [comment]
Typo. Look at a screen of your text (which you would have seen if you'd formatted the comment here)

```
[program:o2s]
directory = /pista/o2s
command = /pista/02s.py
```

![jmbp-1716](https://cloud.githubusercontent.com/assets/60706/8982831/281b954e-36c5-11e5-89ea-b56a1d8e5d5e.png)

**Comment by solucionesmipc** [comment]
Thanks a lot, now it is working fine.

Diego
