### ISSUE TITLE
Implement TLS1.2 support for o2s

### ISSUE THREAD

**Issue by wasmitnetzen** [owntracks/pista#36]
It seems that having o2s support TLS version 1.2 is just a matter of adding a config option for that (and using an appropriate Python/openssl version).

I just added 
```python
    if tls_version == 'tlsv1.2':
        tls_version = ssl.PROTOCOL_TLSv1_2
```
after the line [1197 in o2s.py](https://github.com/owntracks/pista/blob/741dbd44b90df82bcd491029f8dfe593b571502e/o2s.py#L1197). Connection runs without problems then.

**Comment by jpmens** [comment]
Done, thank you.
